spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: desafio
      authentication-database: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



